---
- name: Patch Debian Servers
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Remove unnecessary dependencies
      ansible.builtin.apt:
        autoremove: yes
        
    - name: Clean the package cache
      ansible.builtin.apt:
        autoclean: yes
